version: '3'

services:
  db:
    image: mongo:5
    # image: mongo:4.4.18
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
      # - c:\docker\pokedex:/data/db
